import type { OverseerConfig } from '../config.js';

function esc(s: string): string {
  return s.replace(/[<>&'"]/g, (c) =>
    ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', "'": '&apos;', '"': '&quot;' })[c]!,
  );
}

/**
 * Blackmagic ATEM Software Control "Streaming.xml".
 * Dropped into the ATEM Software Control support folder, this adds an
 * "Atem Overseer (Local)" streaming service whose server points at this app's
 * RTMP ingest. The operator then sets each switcher's stream key to its device
 * id (also listed below) so Overseer can match the feed to the right tile.
 *
 * Format mirrors Blackmagic's shipped Streaming.xml (service > servers > profiles).
 */
/** The RTMP ingest an ATEM should publish to: Restreamer when enabled (so it can
 *  fan out), otherwise Overseer's own node-media-server. */
export function ingestTarget(cfg: OverseerConfig): { serviceName: string; baseUrl: string } {
  const r = cfg.restreamer;
  if (r?.enabled) {
    const base = `rtmp://${r.rtmpHost}:${r.rtmpPort}/${r.rtmpApp || 'live'}`;
    return {
      serviceName: 'Restreamer (Atem Overseer split)',
      baseUrl: r.rtmpToken ? `${base}?token=${encodeURIComponent(r.rtmpToken)}` : base,
    };
  }
  return { serviceName: 'Atem Overseer (Local)', baseUrl: `rtmp://${cfg.publicHost}:${cfg.rtmpPort}/live` };
}

export function generateStreamingXml(cfg: OverseerConfig): string {
  const target = ingestTarget(cfg);
  const rtmpBase = target.baseUrl;
  const keys = cfg.devices.map((d) => `    ${esc(d.name)}: stream key = ${esc(d.id)}`).join('\n');
  const profile = (name: string, bitrate: number, audio: number) => `			<profile>
				<name>${name}</name>
				<config resolution="1080p" fps="30">
					<bitrate>${bitrate}</bitrate>
					<audio-bitrate>${audio}</audio-bitrate>
				</config>
				<config resolution="1080p" fps="60">
					<bitrate>${bitrate}</bitrate>
					<audio-bitrate>${audio}</audio-bitrate>
				</config>
				<config resolution="720p" fps="30">
					<bitrate>${Math.round(bitrate / 2)}</bitrate>
					<audio-bitrate>${audio}</audio-bitrate>
				</config>
				<config resolution="720p" fps="60">
					<bitrate>${Math.round(bitrate / 2)}</bitrate>
					<audio-bitrate>${audio}</audio-bitrate>
				</config>
			</profile>`;

  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by Atem Overseer. Local low-latency streaming ingest. -->
<!-- Per-device stream keys:
${keys}
-->
<streaming>
	<service>
		<name>${esc(target.serviceName)}</name>
		<servers>
			<server>
				<name>Primary</name>
				<url>${esc(rtmpBase)}</url>
			</server>
		</servers>
		<profiles>
${profile('Streaming High', 9_000_000, 128_000)}
${profile('Streaming Medium', 6_000_000, 128_000)}
${profile('Streaming Low', 3_000_000, 128_000)}
		</profiles>
	</service>
</streaming>
`;
}

/** Server URL + key for a single device, for the direct setStreamingService path.
 *  Targets Restreamer's ingest when enabled, otherwise Overseer's own. */
export function streamingServiceFor(cfg: OverseerConfig, deviceId: string) {
  const target = ingestTarget(cfg);
  return {
    serviceName: target.serviceName,
    url: target.baseUrl,
    key: deviceId,
    bitrates: [9_000_000, 3_000_000] as [number, number],
  };
}

// ---- Overseer's own config (device fleet + ingest settings) ----

export function generateConfigXml(cfg: OverseerConfig): string {
  const devices = cfg.devices
    .map(
      (d) =>
        `		<device id="${esc(d.id)}" name="${esc(d.name)}" address="${esc(d.address)}" />`,
    )
    .join('\n');
  return `<?xml version="1.0" encoding="utf-8"?>
<atem-overseer version="1">
	<ingest publicHost="${esc(cfg.publicHost)}" rtmpPort="${cfg.rtmpPort}" mediaHttpPort="${cfg.mediaHttpPort}" httpPort="${cfg.httpPort}" />
	<devices>
${devices}
	</devices>
</atem-overseer>
`;
}

export function parseConfigXml(xml: string): Partial<OverseerConfig> {
  const out: Partial<OverseerConfig> = {};
  const ingest = xml.match(/<ingest\b([^>]*)\/>/);
  if (ingest) {
    const attrs = ingest[1];
    const host = attrs.match(/publicHost="([^"]*)"/)?.[1];
    const rtmp = attrs.match(/rtmpPort="(\d+)"/)?.[1];
    const media = attrs.match(/mediaHttpPort="(\d+)"/)?.[1];
    const http = attrs.match(/httpPort="(\d+)"/)?.[1];
    if (host) out.publicHost = host;
    if (rtmp) out.rtmpPort = Number(rtmp);
    if (media) out.mediaHttpPort = Number(media);
    if (http) out.httpPort = Number(http);
  }
  const devices: OverseerConfig['devices'] = [];
  const re = /<device\b([^>]*)\/>/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(xml))) {
    const a = m[1];
    const id = a.match(/id="([^"]*)"/)?.[1];
    const name = a.match(/name="([^"]*)"/)?.[1];
    const address = a.match(/address="([^"]*)"/)?.[1];
    if (id && address) devices.push({ id, name: name || id, address });
  }
  if (devices.length) out.devices = devices;
  return out;
}
